<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eunjung Myoung (ejmyoung@stanford.edu)">
<meta name="dcterms.date" content="2023-10-19">

<title>Replication of Experiment 4 in ‘‘What Predicts Children’s Fixed and Growth Intelligence Mindsets? Not Their Parents’ View of Intelligence but Their Parents’ View of Failure’ by Haimovitz and Dweck (2016, Psychological Science)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="1022_Replication Report Template_files/libs/clipboard/clipboard.min.js"></script>
<script src="1022_Replication Report Template_files/libs/quarto-html/quarto.js"></script>
<script src="1022_Replication Report Template_files/libs/quarto-html/popper.min.js"></script>
<script src="1022_Replication Report Template_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="1022_Replication Report Template_files/libs/quarto-html/anchor.min.js"></script>
<link href="1022_Replication Report Template_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="1022_Replication Report Template_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="1022_Replication Report Template_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="1022_Replication Report Template_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="1022_Replication Report Template_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#short-justification-for-my-choice-of-experiment." id="toc-short-justification-for-my-choice-of-experiment." class="nav-link" data-scroll-target="#short-justification-for-my-choice-of-experiment.">Short justification for my choice of experiment.</a></li>
  <li><a href="#a-description-of-the-stimuli-and-procedures-that-will-be-required-to-conduct-this-experiment-and-the-expected-challenges." id="toc-a-description-of-the-stimuli-and-procedures-that-will-be-required-to-conduct-this-experiment-and-the-expected-challenges." class="nav-link" data-scroll-target="#a-description-of-the-stimuli-and-procedures-that-will-be-required-to-conduct-this-experiment-and-the-expected-challenges.">A description of the stimuli and procedures that will be required to conduct this experiment, and the expected challenges.</a></li>
  </ul></li>
  <li><a href="#summary-of-prior-replication-attempt" id="toc-summary-of-prior-replication-attempt" class="nav-link" data-scroll-target="#summary-of-prior-replication-attempt">Summary of prior replication attempt</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#power-analysis" id="toc-power-analysis" class="nav-link" data-scroll-target="#power-analysis">Power Analysis</a></li>
  <li><a href="#planned-sample" id="toc-planned-sample" class="nav-link" data-scroll-target="#planned-sample">Planned Sample</a></li>
  <li><a href="#materials" id="toc-materials" class="nav-link" data-scroll-target="#materials">Materials</a></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan">Analysis Plan</a></li>
  <li><a href="#differences-from-original-study-and-1st-replication" id="toc-differences-from-original-study-and-1st-replication" class="nav-link" data-scroll-target="#differences-from-original-study-and-1st-replication">Differences from Original Study and 1st replication</a></li>
  <li><a href="#methods-addendum-post-data-collection" id="toc-methods-addendum-post-data-collection" class="nav-link" data-scroll-target="#methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data preparation</a></li>
  <li><a href="#results-of-control-measures" id="toc-results-of-control-measures" class="nav-link" data-scroll-target="#results-of-control-measures">Results of control measures</a></li>
  <li><a href="#confirmatory-analysis" id="toc-confirmatory-analysis" class="nav-link" data-scroll-target="#confirmatory-analysis">Confirmatory analysis</a></li>
  <li><a href="#exploratory-analyses" id="toc-exploratory-analyses" class="nav-link" data-scroll-target="#exploratory-analyses">Exploratory analyses</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#mini-meta-analysis" id="toc-mini-meta-analysis" class="nav-link" data-scroll-target="#mini-meta-analysis">Mini meta analysis</a>
  <ul class="collapse">
  <li><a href="#summary-of-replication-attempt" id="toc-summary-of-replication-attempt" class="nav-link" data-scroll-target="#summary-of-replication-attempt">Summary of Replication Attempt</a></li>
  <li><a href="#commentary" id="toc-commentary" class="nav-link" data-scroll-target="#commentary">Commentary</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of Experiment 4 in ‘‘What Predicts Children’s Fixed and Growth Intelligence Mindsets? Not Their Parents’ View of Intelligence but Their Parents’ View of Failure’ by Haimovitz and Dweck (2016, Psychological Science)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eunjung Myoung (ejmyoung@stanford.edu) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 19, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="short-justification-for-my-choice-of-experiment." class="level3">
<h3 class="anchored" data-anchor-id="short-justification-for-my-choice-of-experiment.">Short justification for my choice of experiment.</h3>
<p>My choice of experiment aligns with my research interests in the field of education, particularly in the area of students’ intelligence mindset. Throughout my master’s program, I delved into the fascinating debate surrounding fixed and growth mindsets among students. Additionally, I have explored research articles investigating the connection between parents’ mindsets and their children’s mindset development. However, the unique focus of this experiment on parents’ failure mindset and its potential influence on students’ intelligence mindset offers a fresh perspective. This study promises to contribute significantly to my understanding of the factors that shape students’ intelligence mindsets, making it a valuable addition to my research program.</p>
</section>
<section id="a-description-of-the-stimuli-and-procedures-that-will-be-required-to-conduct-this-experiment-and-the-expected-challenges." class="level3">
<h3 class="anchored" data-anchor-id="a-description-of-the-stimuli-and-procedures-that-will-be-required-to-conduct-this-experiment-and-the-expected-challenges.">A description of the stimuli and procedures that will be required to conduct this experiment, and the expected challenges.</h3>
<p>This experiment aimed to investigate whether <strong>parents’ failure mindsets have a causal effect on their reactions to their children’s failures</strong>. The procedures of this experiments might include the following steps; 1) Recruit the parents 2) Pre-assess the parents’ current beliefs and perceptions of their child’s competence 3) Randomly assign parents to two groups to manipulate their their failure mindset (i.e., failure-is-debilitating mind-set and failure-is- enhancing mind-set) 5) Ask participants to imagine their child’s failure in math quiz and write their response 6) Post-assess parents’ failure mindset after manipulation 7) Code the open-ended responses 8) Finally analyze the data and report the result.</p>
<p>However, crafting effective questionnaires that genuinely manipulate the desired mindset can be challenging. Moreover, even though we attempt to randomly assign participants to one of the two questionnaire conditions, ensuring truly random assignment can be difficult due to factors such as participants’ personal biases or demographic information, which may affect the mindset manipulation. Additionally, when analyzing the results of the intervention, the parents’ responses regarding their feelings related to their child’s supposed failure on a math quiz are in an open-ended descriptive format. This means that researchers should code the open-ended responses into performance-oriented and learning-oriented responses, a process that can be subject to inter-rater variability. Maintaining high reliability between coders is essential.</p>
<p>A link to the repository and to the original paper is <a href="https://github.com/ejmyoung/haimovitz2016_1_rescue/blob/2bc755e2cf8879bf63977180987b8e5d52d2532f/original_paper/%20Parents%E2%80%99%20Views%20of%20Failure%20Predict%20Children%E2%80%99s%20Fixed%20and%20Growth%20Intelligence%20Mind-Sets.pdf">“here”</a>.</p>
</section>
</section>
<section id="summary-of-prior-replication-attempt" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-prior-replication-attempt">Summary of prior replication attempt</h2>
<p>Based on the prior write-up, describe any differences between the original and 1st replication in terms of methods, sample, sample size, and analysis.</p>
<table class="table">
<colgroup>
<col style="width: 5%">
<col style="width: 42%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Original paper</th>
<th>First replication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample size</td>
<td>n = 132</td>
<td>n = 115</td>
</tr>
<tr class="even">
<td>Sample characteristics</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>1)Gender</td>
<td>Female (57%)</td>
<td>Female (49%), genderqueer, gender fluid, or non-binary (2%)</td>
</tr>
<tr class="even">
<td>2)Education</td>
<td>High school diploma or some college education (31%), College degree (51%), Postgraduate degree (18%)</td>
<td>No degrees (1%), High school diploma (24%), College degree (55%), Post-graduate degree (19%), Preferred not to answer (1%)</td>
</tr>
<tr class="odd">
<td>3)Race/Ethnicity</td>
<td>White (75%), African American (12%), Asian American (7%), Hispanic (6%)</td>
<td>White (63%), Black/African American (16%), Asian (4%), Hispanic, Latino or Spanish origin (17%), Native Hawaiian or Other Pacific Islander (1%), Filled in their own option (3%), Preferred not to answer (1%)</td>
</tr>
<tr class="even">
<td>Crowdsourcing Platform</td>
<td>Amazon’s Mechanical Turk Web</td>
<td>Prolific</td>
</tr>
<tr class="odd">
<td>Analysis</td>
<td>Unpaired, Two-Tailed T-Test</td>
<td>Unpaired, Two-Tailed T-Test</td>
</tr>
<tr class="even">
<td>Coder</td>
<td>Two coders: rated 20 responses (15%).(performance-oriented responses: ICC = .91; learning- oriented responses: ICC = .90).</td>
<td>one coder</td>
</tr>
<tr class="odd">
<td>Data exclusion</td>
<td>did not mention for the exclusion</td>
<td>exclude data from participants if the open-ended responses were not possible to code (e.g., unintelligible responses, responses such as “I don’t know.”).</td>
</tr>
<tr class="even">
<td>Result</td>
<td><strong>Parents who were induced to hold a failure-is-debilitating mind-set were more likely to react with concerns about their child’s performance and lack of ability</strong> t(131) = 3.246, p &lt; .001, ηp2 = .075</td>
<td>showed similar trends to this original finding. But, the <strong>effect was not as large and there was no statistical difference in the number of performance-oriented responses between the two condition</strong>s, t(113) = -1.9291, p = 0.0562, ηp2 = .031.</td>
</tr>
</tbody>
</table>
<p>In addition to the original research, the replication study examined demographic variables such as the child’s age, parents’ socioeconomic status (specifically, education level), parents’ gender, and parents’ race/ethnicity. The study also investigated the relationship between parents’ prior knowledge of mindset research and their learning-oriented and performance-oriented responses.</p>
<p>While the replication study provided a transparent account of the sampling process and data analysis, it had limitations. Specifically, the study employed only a single coder, making it impossible to assess inter-coder reliability.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="power-analysis" class="level3">
<h3 class="anchored" data-anchor-id="power-analysis">Power Analysis</h3>
<p>Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size. Considerations of feasibility for selecting planned sample size.</p>
<p>How much power does your planned sample have for original effect? For an attenuated effect that is half the size of the original?</p>
<p>(If power analysis is not possible or precise, discuss more fully how you determined a sample size that would be sufficient for rescue.)</p>
</section>
<section id="planned-sample" class="level3">
<h3 class="anchored" data-anchor-id="planned-sample">Planned Sample</h3>
<p>In the <strong>original study</strong>, 310 adults from a crowdsourcing platform called Amazon Mechanical Turk completed an initial survey asking whether they were a parent. Out of these adults, <strong>132 participants</strong> reported to be a parent and were chosen to participate in the study.</p>
<p>In the <strong>first replication study</strong>, 119 parents were recruited and <strong>115 participants</strong> were finally analyzed.</p>
<p><strong>This study plan to recruit the parents from prolific; 150 parents (75 mothers and 74 fathers).</strong> Because, the result of first replication study was not significant compared to the original paper and the replicator mentioned that; &gt; However, I think my replication was rather successful, given that my sample size was smaller.</p>
<p>Therefore, this study tried to collect the data more than original participants (n = 132) to differentiate the sample size from the previous research. Parents were recruited through a crowdsourcing platform called Prolific. The participant pool on Prolific was filtered by parental status to specifically reach parents.</p>
</section>
<section id="materials" class="level3">
<h3 class="anchored" data-anchor-id="materials">Materials</h3>
<section id="general-materials-and-procedures" class="level4">
<h4 class="anchored" data-anchor-id="general-materials-and-procedures">General Materials and Procedures</h4>
<p>This study followed the materials and procedures outlined in the original article same as the first replication study.</p>
<p>All survey items outlined in the supplementary <a href="https://osf.io/hb583">“Materials and Measures”</a> document were used.</p>
<blockquote class="blockquote">
<p>Participants completed an online survey initially assessing several beliefs, including their perceptions of their child’s competence (assessed with same measure as in Study 1; α = .79). Then we temporarily manipulated failure mind-sets by randomly assigning the parents to complete one of two five-item biased questionnaires, written to foster agreement with either a failure-is-debilitating mind-set (e.g., “Experienc- ing failure can lead to negative feelings, like shame or sadness, that interfere with learning”) or a failure-is- enhancing mind-set (e.g., “Experiencing failure can improve performance in the long run if you learn from it”). All measures used a 6-point rating scale from 1 (strongly disagree) to 6 (strongly agree). One-sample t tests comparing the mean in each priming condition with the scale’s midpoint (3.5) showed that participants’ agree- ment with the intended mind-set was above the midpoint in both the failure-is-debilitating condition (M = 4.41, SD = 1.07), t(56) = 6.45, p &lt; .001, and the failure-is- enhancing condition (M = 5.14, SD = 0.829), t(74) = 17.11, p &lt; .001.</p>
</blockquote>
<blockquote class="blockquote">
<p>We then asked participants to read and vividly imagine a scenario in which their child came home from school with a failing grade on a math quiz, as in Study 2. They then wrote what they would do, think, and feel in response. Finally, participants reported on their failure mind-sets (α = .82), using the same items as in Study 1, as part of a survey that included a few other items.</p>
</blockquote>
<p>The first replication study highlighted the ambiguity of the Likert scale used in the original article, as well as the lack of clarity in the collected demographic data: &gt; From reading the original article and supplementary document, it was not clear whether the middle points on the Likert scale were labelled. Based on similar studies examining intelligence mindsets, I decided to label the middle points with “mostly dis/agree” and “slightly dis/agree.” … As I was also not sure where to collect demographic data (i.e., sex, race, education level, child’s age), I decided to collect this information as part of the final survey at the very end of the study.</p>
<p>This study decided to follow this from first replication study.</p>
</section>
<section id="open-ended-responses-coding" class="level4">
<h4 class="anchored" data-anchor-id="open-ended-responses-coding">open-ended responses coding</h4>
<p>The open ended responses were coded following the explanation in the original article and the supplementary document; <a href="https://osf.io/hb583">“Materials and Measures”</a></p>
<blockquote class="blockquote">
<p>Two raters, blind to condition, coded the open- ended responses. The first author developed a coding scheme on the basis of an initial reading of the responses and then made clarifying revisions on the basis of feed- back from the two raters.</p>
</blockquote>
<p>The coding scheme was already developed by the author, this study followed it.</p>
<blockquote class="blockquote">
<p>The codes were broken down into two main categories of interest: performance-oriented responses and learning-oriented responses. Coders gave a score of 1 each time a code was present. Codes in the performance-oriented category were responses that focused on judgments of ability, particularly as a stable trait (e.g., “I would think maybe my child is just not that good at math”); comfort for lack of ability (e.g., “It’s ok that you got an F. You tried your best”); contingent self-worth based on their child’s performance (e.g., “I’d feel bad about myself”); pity for their child’s lack of ability (“I would feel a little nervous for my child because I know how hard it can be”); grades as a goal (e.g., “I would . . . hope their grades from previous [tests] are high enough to make up for the test”); and social comparison (“I would also want to know how the other children in the class scored”). Codes in the learning-oriented category were responses that focused on judgments of effort (e.g., “I would tell my son he needs to study harder”); strategies, which included both general strategies (e.g., “he didn’t study the material in the right way”) and specific study or test-taking strategies (e.g., “I would also say that double checking your work before you hand it in is a good habit to get into”); help seeking (e.g., “I would get her a math tutor”); mastery, or conceptual understanding, as a goal (e.g., “the important thing we need to do is try to understand the concepts behind the problems he got wrong, and then study those”); interest (e.g., “I would hope that the results of the test would not stop her from enjoying the class and wonder about ways I could help keep her liking of the subject going”); and explicit characterizations of failure as enhancing, or good (e.g., “It is ok to make mistakes and fail sometimes, because that’s how people learn”).</p>
</blockquote>
<blockquote class="blockquote">
<p>Two statements that repeated the same sentiment were not coded as two instances (e.g., “I would question how much studying did they do” and “I would also ask . . . do they think they studied enough” would be one code for effort). However, two statements that expressed different ideas but fell under the same code were marked as two instances (e.g., “I would question my child to make sure that she studied the correct material thoroughly” and “I would ask to make sure that she was paying attention in class” would be marked as two codes for strategies, as these statements represent different strategies). If a statement fell under two codes and one was more specific than the other, only the more specific classification was counted. That is, although effort and help seeking can be different types of strategies, statements expressing these ideas were coded only as effort and help seeking, not also as strategies.</p>
</blockquote>
<blockquote class="blockquote">
<p>Scores for performance-oriented and learning-oriented responses were each created by summing all instances of their respective subcategories. Two coders rated 20 responses (15%) to assess reliability.”</p>
</blockquote>
<p>On the other hand, first replication study conducted the coding with one person. &gt; As there was already a coding scheme developed by the original authors, I did not create my own coding scheme. Rather, I carefully reviewed the coding scheme outlined in the supplementary document to code the responses. I considered recruiting an undergraduate RA or another PSYCH 251 student to serve as the second rater, but in the end, I decided to code all of the responses on my own. I came to this decision during the pilot study, when I noticed it takes a while to get used to the coding scheme outlined by the authors. Given that the project needed to be completed in a quarter, it didn’t seem feasible to recruit another student and have them reliably code the responses in this short time frame. By scrambling the responses before downloading and viewing the open-ended responses for coding, I was able to ensure that I remained blind to condition.</p>
<p>This study will follow the orignial paper by recruiting the other coder besides me.</p>
</section>
</section>
<section id="analysis-plan" class="level3">
<h3 class="anchored" data-anchor-id="analysis-plan">Analysis Plan</h3>
<p>The key analysis of interest will be an <strong>unpaired, two-tailed t-test comparing performance-oriented responses between the two conditions</strong>. The analysis will aim to replicate the following result:</p>
<blockquote class="blockquote">
<p>Parents who were induced to hold a failure-is-debilitating mind-set were more likely to react with concerns about their child’s per- formance and lack of ability, t(131) = 3.246, p &lt; .001, ηp2 = .075, and less likely to react with support for their child’s learning and mastery, t(131) = −2.04, p = .043, ηp2 = .031, compared with those who were induced to hold a failure-is-enhancing mind-set (see Fig. 2). Parents in both conditions did not report performance-oriented responses (M = 0.485, SD = 0.693) nearly as often as learning-oriented responses (M = 2.38, SD = 1.53).</p>
</blockquote>
<p>Moreover, the 1st replication study did exploratory analysis. &gt; Apart from any of the analyses reported in the original study, I also explored whether parents’ knowledge of mindset research was associated with their learning-oriented and performance-oriented responses.</p>
<p>This study aim to replicate this exploratory analysis too.</p>
</section>
<section id="differences-from-original-study-and-1st-replication" class="level3">
<h3 class="anchored" data-anchor-id="differences-from-original-study-and-1st-replication">Differences from Original Study and 1st replication</h3>
<p>To summarize the distinctions between the original study, the first replication, and the present study: Firstly, the current research aims to recruit 150 parents, a sample size larger than those in the original study and the first replication. This increase in sample size is anticipated to analyze whether the failure to replicate the original research in the first study was due to a smaller sample size. Secondly, this research intends to code the open-ended responses with two coders, adhering to the method employed in the original study. This approach can address the limitations identified in the first replication study. Lastly, this study will reproduce the explanatory analysis conducted in the first replication, specifically examining the relationship between parents’ prior knowledge of failure mindset and their learning-oriented and performance-oriented responses. This endeavor offers an additional opportunity to validate the findings of the first replication study.</p>
</section>
<section id="methods-addendum-post-data-collection" class="level3">
<h3 class="anchored" data-anchor-id="methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</h3>
<p>You can comment this section out prior to final report with data collection.</p>
<section id="actual-sample" class="level4">
<h4 class="anchored" data-anchor-id="actual-sample">Actual Sample</h4>
<p>Sample size, demographics, data exclusions based on rules spelled out in analysis plan</p>
</section>
<section id="differences-from-pre-data-collection-methods-plan" class="level4">
<h4 class="anchored" data-anchor-id="differences-from-pre-data-collection-methods-plan">Differences from pre-data collection methods plan</h4>
<p>Any differences from what was described as the original plan, or “none”.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data preparation</h3>
<p>Data preparation following the analysis plan.</p>
</section>
<section id="results-of-control-measures" class="level3">
<h3 class="anchored" data-anchor-id="results-of-control-measures">Results of control measures</h3>
<p>How did people perform on any quality control checks or positive and negative controls?</p>
</section>
<section id="confirmatory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="confirmatory-analysis">Confirmatory analysis</h3>
<p>Main Analysis of Interest: <strong>Were parents who hold a failure-is-debilitating mind-set more likely to react with concerns about their child’s performance and lack of ability?</strong></p>
<p>Original Study Result &gt; “Parents who were induced to hold a failure-is-debilitating mind-set were more likely to react with concerns about their child’s performance and lack of ability, t(131) = 3.246, p &lt; .001, ηp2 = .075 … compared with those who were induced to hold a failure-is-enhancing mind-set.”</p>
<p><em>Three-panel graph with original, 1st replication, and your replication is ideal here</em> <strong>original research result</strong> <img src="/Users/myeong-eunjeong/Library/CloudStorage/OneDrive-Stanford/PSYCH%20251/original%20figure.png" class="img-fluid" alt="Alt"></p>
<p><strong>1st replication research result</strong> <img src="/Users/myeong-eunjeong/Library/CloudStorage/OneDrive-Stanford/PSYCH%20251/1st%20replication%20figure.png" class="img-fluid" alt="Alt"></p>
</section>
<section id="exploratory-analyses" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-analyses">Exploratory analyses</h3>
<p>Any follow-up analyses desired (not required).</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
</section>
<section id="mini-meta-analysis" class="level2">
<h2 class="anchored" data-anchor-id="mini-meta-analysis">Mini meta analysis</h2>
<p>Combining across the original paper, 1st replication, and 2nd replication, what is the aggregate effect size?</p>
<section id="summary-of-replication-attempt" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-replication-attempt">Summary of Replication Attempt</h3>
<p>Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.</p>
</section>
<section id="commentary" class="level3">
<h3 class="anchored" data-anchor-id="commentary">Commentary</h3>
<p>Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt. None of these need to be long.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>