---
title: "Replication of Experiment 4 in '‘What Predicts Children’s Fixed and Growth Intelligence Mindsets? Not Their Parents’ View of Intelligence but Their Parents’ View of Failure’ by Haimovitz and Dweck (2016, Psychological Science)"
author: "Eunjung Myoung (ejmyoung@stanford.edu)"
date: "`r format(Sys.time(), '%10 %19, %2023')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

### Short justification for my choice of experiment.

My choice of experiment aligns with my research interests in the field of education, particularly in the area of students' intelligence mindset. Throughout my master's program, I delved into the fascinating debate surrounding fixed and growth mindsets among students. Additionally, I have explored research articles investigating the connection between parents' mindsets and their children's mindset development. However, the unique focus of this experiment on parents' failure mindset and its potential influence on students' intelligence mindset offers a fresh perspective. This study promises to contribute significantly to my understanding of the factors that shape students' intelligence mindsets, making it a valuable addition to my research program.

### A description of the stimuli and procedures that will be required to conduct this experiment, and the expected challenges.

This experiment aimed to investigate whether **parents' failure mindsets have a causal effect on their reactions to their children's failures**. The procedures of this experiments might include the following steps; 1) Recruit the parents 2) Pre-assess the parents' current beliefs and perceptions of their child's competence 3) Randomly assign parents to two groups to manipulate their their failure mindset (i.e., failure-is-debilitating mind-set and failure-is- enhancing mind-set) 5) Ask participants to imagine their child's failure in math quiz and write their response 6) Post-assess parents' failure mindset after manipulation 7) Code the open-ended responses 8) Finally analyze the data and report the result.

However, crafting effective questionnaires that genuinely manipulate the desired mindset can be challenging. Moreover, even though we attempt to randomly assign participants to one of the two questionnaire conditions, ensuring truly random assignment can be difficult due to factors such as participants' personal biases or demographic information, which may affect the mindset manipulation. Additionally, when analyzing the results of the intervention, the parents' responses regarding their feelings related to their child's supposed failure on a math quiz are in an open-ended descriptive format. This means that researchers should code the open-ended responses into performance-oriented and learning-oriented responses, a process that can be subject to inter-rater variability. Maintaining high reliability between coders is essential.

A link to the repository and to the original paper is <a href="https://github.com/ejmyoung/haimovitz2016_1_rescue/blob/2bc755e2cf8879bf63977180987b8e5d52d2532f/original_paper/%20Parents%E2%80%99%20Views%20of%20Failure%20Predict%20Children%E2%80%99s%20Fixed%20and%20Growth%20Intelligence%20Mind-Sets.pdf">"here"</a>. 


## Summary of prior replication attempt

Based on the prior write-up, describe any differences between the original and 1st replication in terms of methods, sample, sample size, and analysis.

|                        | Original paper                                                                                                                                                                                         | First replication                                                                                                                                                                                                                                |
|------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Sample size            | n = 131                                                                                                                                                                                                | n = 113                                                                                                                                                                                                                                          |
| Sample characteristics |                                                                                                                                                                                                        |                                                                                                                                                                                                                                                  |
| 1)Gender               | Female (57%)                                                                                                                                                                                           | Female (49%), genderqueer, gender fluid, or non-binary (2%)                                                                                                                                                                                      |
| 2)Education            | High school diploma or some college education (31%), College degree (51%), Postgraduate degree (18%)                                                                                                   | No degrees (1%), High school diploma (24%),  College degree (55%), Post-graduate degree (19%),  Preferred not to answer (1%)                                                                                                                     |
| 3)Race/Ethnicity       | White (75%), African American (12%),  Asian American (7%), Hispanic (6%)                                                                                                                               | White (63%), Black/African American (16%), Asian (4%), Hispanic, Latino or Spanish origin (17%),  Native Hawaiian or Other Pacific Islander (1%), Filled in their own option (3%), Preferred not to answer (1%)                                  |
| Crowdsourcing Platform | Amazon’s Mechanical Turk Web                                                                                                                                                                           | Prolific                                                                                                                                                                                                                                         |
| Analysis               | Unpaired, Two-Tailed T-Test                                                                                                                                                                            | Unpaired, Two-Tailed T-Test                                                                                                                                                                                                                      |
| Coder                  | Two coders: rated 20 responses (15%).(performance-oriented responses: ICC = .91; learning- oriented responses: ICC = .90).                                                                             | one coder                                                                                                                                                                                                                                        |
| Data Exclusion         | did not mention for the exclusion                                                                                                                                                                      | exclude data from participants  if the open-ended responses were not possible to code  (e.g., unintelligible responses, responses such as “I don’t know.”).                                                                                      |
| Result                 | Parents who were induced to hold a failure-is-debilitating mind-set were more likely to react with concerns about  their child’s performance and lack of ability  t(131) = 3.246, p < .001, ηp2 = .075 | showed similar trends to this original finding. But, the effect was not as large and there was no statistical difference  in the number of performance-oriented responses between the two conditions,  t(113) = -1.9291, p = 0.0562, ηp2 = .031. |

Note any potential problems such as exclusion rates, noisy data, or issues with analysis.

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size. Considerations of feasibility for selecting planned sample size.

How much power does your planned sample have for original effect? For an attenuated effect that is half the size of the original?

(If power analysis is not possible or precise, discuss more fully how you determined a sample size that would be sufficient for rescue.)

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

#### General Materials and Procedures
The replication study followed the materials and procedures outlined in the original article:

> Participants completed an online survey initially assessing several beliefs, including their perceptions of their child’s competence (assessed with same measure as in Study 1; α = .79). Then we tem- porarily manipulated failure mind-sets by randomly assigning the parents to complete one of two five-item biased questionnaires, written to foster agreement with either a failure-is-debilitating mind-set (e.g., “Experienc- ing failure can lead to negative feelings, like shame or sadness, that interfere with learning”) or a failure-is- enhancing mind-set (e.g., “Experiencing failure can improve performance in the long run if you learn from it”). All measures used a 6-point rating scale from 1 (strongly disagree) to 6 (strongly agree). One-sample t tests comparing the mean in each priming condition with the scale’s midpoint (3.5) showed that participants’ agree- ment with the intended mind-set was above the midpoint in both the failure-is-debilitating condition (M = 4.41, SD = 1.07), t(56) = 6.45, p < .001, and the failure-is- enhancing condition (M = 5.14, SD = 0.829), t(74) = 17.11, p < .001.

> We then asked participants to read and vividly imag- ine a scenario in which their child came home from school with a failing grade on a math quiz, as in Study 2. They then wrote what they would do, think, and feel in response. Finally, participants reported on their failure mind-sets (α = .82), using the same items as in Study 1, as part of a survey that included a few other items.

All survey items outlined in the supplementary <a href="https://osf.io/hb583">"Materials and Measures"</a> document were used.


### Procedure

Can quote directly from original article - just put the text in quotations and note that this was followed precisely. Or, quote directly and just point out exceptions to what was described in the original article.

### Controls

What attention checks, positive or negative controls, or other quality control measures are you adding so that a (positive or negative) result will be more interpretable?

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section. The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.

**Clarify key analysis of interest here** You can also pre-specify additional analyses you plan to do.

### Differences from Original Study and 1st replication

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study. The goal, of course, is to minimize those differences, but differences will inevitably occur. Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample

Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan

Any differences from what was described as the original plan, or "none".

## Results

### Data preparation

Data preparation following the analysis plan.

```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Results of control measures

How did people perform on any quality control checks or positive and negative controls?

### Confirmatory analysis

The analyses as specified in the analysis plan.

*Three-panel graph with original, 1st replication, and your replication is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).


## Discussion

## Mini meta analysis

Combining across the original paper, 1st replication, and 2nd replication, what is the aggregate effect size?

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt. None of these need to be long.
